#-------------------------------------------------------------------------
# TITLE:
#    pkgIndex.tcl
#
# PROJECT:
#    athena-sim - Athena Regional Stability Simulation
#
# DESCRIPTION:
#    app_athena(n) package index file
#
#    Generated by Kite.
#-------------------------------------------------------------------------

# -kite-ifneeded-start  DO NOT EDIT THIS BLOCK BY HAND
package ifneeded app_athena 6.3.1a0 [list source [file join $dir pkgModules.tcl]]
# -kite-ifneeded-end

# Functionality Packages
# TBD: Probably want to do this differently.

package ifneeded app_sim_shared 1.0 \
    [list source [file join $dir shared app_sim_shared.tcl]]

package ifneeded app_sim_ui 1.0 \
    [list source [file join $dir ui app_sim_ui.tcl]]

package ifneeded wnbhood 1.0 \
    [list source [file join $dir wnbhood pkgModules.tcl]]

package ifneeded wintel 1.0 \
    [list source [file join $dir wintel pkgModules.tcl]]


