#---------------------------------------------------------------------
# TITLE:
#    Makefile -- Man Page Section (sim)
#
# AUTHOR:
#    Will Duquette
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# Settings

TOP_DIR    = ../..
TARGETS    = man
MANSECTION = "(sim): minerva_sim(1) Internals"
CLEANFILES = *.gif

#---------------------------------------------------------------------
# Use Standard Rules

include ../MakeMan

