#-----------------------------------------------------------------------
# TITLE:
#    icons.tcl
#
# AUTHOR:
#    Will Duquette
#
# DESCRIPTION:
#    projectgui(n) package: standard icons
#
#    This module defines a set of standard icons for use in buttons,
#    etc.  All icons are defined in the ::projectgui::icon namespace; none
#    are exported.
#
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Icon definitions

namespace eval ::projectgui::icon:: {
    namespace import ::marsgui::mkicon

    mkicon ::projectgui::icon::pencil22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X.........
        ....XwwX,,,X..........
        ...XwwwwX,X...........
        ...XwwwwwX............
        ...XXwwXX.............
        ..XXXXX...............
        ..XX..................
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    }

    mkicon ::projectgui::icon::plus22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ......................
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }

    mkicon ::projectgui::icon::x22 {
        ......................
        ......................
        ......................
        ...XX............XX...
        ...XXX..........XXX...
        ....XXX........XXX....
        .....XXX......XXX.....
        ......XXX....XXX......
        .......XXX..XXX.......
        ........XXXXXX........
        .........XXXX.........
        .........XXXX.........
        ........XXXXXX........
        .......XXX..XXX.......
        ......XXX....XXX......
        .....XXX......XXX.....
        ....XXX........XXX....
        ...XXX..........XXX...
        ...XX............XX...
        ......................
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }
}


