#-----------------------------------------------------------------------
# TITLE:
#    icons.tcl
#
# AUTHOR:
#    Will Duquette
#
# DESCRIPTION:
#    projectgui(n) package: standard icons
#
#    This module defines a set of standard icons for use in buttons,
#    etc.  All icons are defined in the ::projectgui::icon namespace; none
#    are exported.
#
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Icon definitions

namespace eval ::projectgui::icon:: {
    namespace import ::marsgui::mkicon

    mkicon ::projectgui::icon::pencil022 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X..XXXX...
        ....XwwX,,,X..X....X..
        ...XwwwwX,X...X...XX..
        ...XwwwwwX....X..X.X..
        ...XXwwXX.....X.X..X..
        ..XXXXX.......XX...X..
        ..XX...........XXXX...
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }

    mkicon ::projectgui::icon::pencils22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X..XXXX...
        ....XwwX,,,X..X....X..
        ...XwwwwX,X...X.......
        ...XwwwwwX.....XXXX...
        ...XXwwXX..........X..
        ..XXXXX.......X....X..
        ..XX...........XXXX...
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }

    mkicon ::projectgui::icon::pencila22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X..XXXX...
        ....XwwX,,,X..X....X..
        ...XwwwwX,X...X....X..
        ...XwwwwwX....XXXXXX..
        ...XXwwXX.....X....X..
        ..XXXXX.......X....X..
        ..XX..........X....X..
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }


    mkicon ::projectgui::icon::pencili22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X..XXXXX..
        ....XwwX,,,X.....X....
        ...XwwwwX,X......X....
        ...XwwwwwX.......X....
        ...XXwwXX........X....
        ..XXXXX..........X....
        ..XX...........XXXXX..
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    } d { X gray  e gray  w gray82  , gray82 }


    mkicon ::projectgui::icon::locked22 {
        ......................
        ......XXXXXXXXXX......
        .....XXXXXXXXXXXX.....
        .....XX........XX.....
        .....XX........XX.....
        .....XX........XX.....
        .....XX........XX.....
        ...XXXXXXXXXXXXXXXX...
        ...X..............X...
        ...X...XXXXXXX....X...
        ...X...XXXXXXXX...X...
        ...X...XX....XX...X...
        ...X...XX....XX...X...
        ...X...XX....XX...X...
        ...X...XXXXXXXX...X...
        ...X...XXXXXXX....X...
        ...X...XX.........X...
        ...X...XX.........X...
        ...X...XX.........X...
        ...X..............X...
        ...XXXXXXXXXXXXXXXX...
        ......................
    } { . trans X black } d { X gray }

    mkicon ::projectgui::icon::unlocked22 {
        ......................
        ......XXXXXXXXXX......
        .....XXXXXXXXXXXX.....
        .....XX........XX.....
        .....XX........XX.....
        .....XX...............
        .....XX...............
        ...XXXXXXXXXXXXXXXX...
        ...X..............X...
        ...X...XXXXXXX....X...
        ...X...XXXXXXXX...X...
        ...X...XX....XX...X...
        ...X...XX....XX...X...
        ...X...XX....XX...X...
        ...X...XXXXXXXX...X...
        ...X...XXXXXXX....X...
        ...X...XX.........X...
        ...X...XX.........X...
        ...X...XX.........X...
        ...X..............X...
        ...XXXXXXXXXXXXXXXX...
        ......................
    } { . trans X black } d { X gray }



    mkicon ::projectgui::icon::nbpoly {
        ..XX..........
        ..X.XX........
        ..X...XX......
        ..X.....XX....
        .X........XX..
        .X..........XX
        .X...........X
        .X..X.....X..X
        X...XX....X..X
        X...X.X...X..X
        X...X..X..X..X
        X...X...X.X..X
        .X..X....XX..X
        .X..X.....X..X
        .X...........X
        .X.........XXX
        ..X.....XXX...
        ..X..XXX......
        ..XXX.........
    } { . trans  X black } d { X gray }


    mkicon ::projectgui::icon::plust22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX..XXXXX..
        .........XXXX....X....
        .........XXXX....X....
        .........XXXX....X....
        .........XXXX....X....
        ......................
        ......................
        ......................
    } { . trans  X black } d { X gray }


    mkicon ::projectgui::icon::home22 {
        ......................
        ......................
        ......................
        ..........XX...XX.....
        .........XXXX..XX.....
        ........XXXXXX.XX.....
        .......XXXXXXXXXX.....
        ......XXXXXXXXXXX.....
        .....XXXXXXXXXXXX.....
        ....XXXXXXXXXXXXXX....
        ...XXXXXXXXXXXXXXXX...
        ..XXXXXXXXXXXXXXXXXX..
        .XXXXXXXXXXXXXXXXXXXX.
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXXXX....
        ....XXXXXX..XXXXXX....
        ....XXXXXX..XXXXXX....
        ....XXXXXX..XXXXXX....
        ....XXXXXX..XXXXXX....
        ......................
    } {
        .  trans
        X  #000000
    } d { X gray }

    mkicon ::projectgui::icon::trash22 {
        ....................
        ....................
        .......XXXX........
        ......X....X.......
        ..XXXXXXXXXXXXXX..
        .XeeeeeeeeeeeeeeX.
        .XXXXXXXXXXXXXXXX.
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XeXeeXeeXeeXeX..
        ..XXXXXXXXXXXXXX..
        ....................
    } {
        .  trans
        X  black
        e  gray
    } d { X gray }

    mkicon ::projectgui::icon::actor12 {
        ..XX..
        .XXXX.
        .XXXX.
        ..XX..
        XXXXXX
        X.XX.X
        X.XX.X
        ..XX..
        .XXXX.
        .X..X.
        .X..X.
        .X..X.
    } { . trans X black }

    mkicon ::projectgui::icon::nbhood12 {
        .......
        ...X...
        ..XXX..
        .XX,XX.
        XX,,,XX
        X,,,,,X
        .X,,,,X
        .X,,,,X
        X,,,,,X
        XX,,,,X
        ..XX,,X
        ....XX.
    } { . trans , "#00AA00" X black }

    mkicon ::projectgui::icon::group12 {
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
    } { . trans X black }

    mkicon ::projectgui::icon::frcgroup12 {
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
    } { . trans X "#CC0000" }

    mkicon ::projectgui::icon::civgroup12 {
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
    } { . trans X "#00AA00" }

    mkicon ::projectgui::icon::orggroup12 {
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
        ...X...
        ..XXX..
        ...X...
        .X...X.
        XXX.XXX
        .X...X.
    } { . trans X "#0000FF" }

    mkicon ::projectgui::icon::folder12 {
        ............
        ......XXXX..
        .....X,,,,X.
        XXXXXXXXXXXX
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        XXXXXXXXXXXX
    } { . trans X black , "#0AAEBD" }

    mkicon ::projectgui::icon::page12 {
        ....XXXXXXXX
        ...XX,,,,,,X
        ..X,X,,,,,,X
        .X,,X,,,,,,X
        XXXXX,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        X,,,,,,,,,,X
        XXXXXXXXXXXX
    } { . trans X black , white }

    mkicon ::projectgui::icon::help12 {
        ...XXXXXX...
        ..XX....XX..
        ..XX.....XX.
        ........XX..
        .......XX...
        ......XX....
        .....XX.....
        .....XX.....
        ............
        .....XX.....
        ....XXXX....
        .....XX.....
    } { . trans X black , white }

    mkicon ::projectgui::icon::eye12 {
        ............
        ............
        ..X..X..X...
        X..XXXXX..X.
        .XX.....XX..
        XX..XXX..XX.
        X..XXXXX..X.
        XX..XXX..XX.
        .XX.....XX..
        ...XXXXX....
        ............
        ............
    } { . trans X black , "#0AAEBD" }

    mkicon ::projectgui::icon::pencil12 {
        ............
        .......XX...
        ......X,,X..
        .....X,,,X..
        ....X,,,X...
        ...X,,,X....
        ..X,,,X.....
        .XwX,X......
        .XwwX.......
        .XXX........
        XX..........
        X...........
    } { . trans 
        X black 
        ,  #EFB311
        w  #BDA565
    } d {X gray w gray82 , gray82}
}


