#-----------------------------------------------------------------------
# TITLE:
#    pkgModules.tcl
#
# PROJECT:
#    athena-sim - Athena Regional Stability Simulation
#
# DESCRIPTION:
#    athenaapp(n) package modules file
#
#    Generated by Kite.
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Package Definition

# -kite-provide-start  DO NOT EDIT THIS BLOCK BY HAND
package provide athenaapp 6.3.1a0
# -kite-provide-end


#-----------------------------------------------------------------------
# Required Packages

# Add 'package require' statements for this package's external 
# dependencies to the following block.  Kite will update the versions 
# numbers automatically as they change in project.kite.

# -kite-require-start ADD EXTERNAL DEPENDENCIES
package require snit 2.3
package require sqlite3 3.8.5
package require textutil::adjust 0.7
package require kiteutils 0.3.1a0
package require marsutil 3.0.1a0
package require simlib 3.0.1a0
package require projectlib

namespace import ::projectlib::*

# For Tk applications
if {$::loadTk} {
    # From Mars
    package require marsgui 3.0.1a0

    # From Athena
    package require projectgui

    namespace import ::marsgui::*
    namespace import ::projectgui::*

    package require app_sim_ui
    package require wnbhood
    package require wintel
}

# -kite-require-end

package require app_sim_shared

#-----------------------------------------------------------------------
# Namespace definition

namespace eval ::athenaapp:: {
    variable library [file dirname [info script]]
}

#-----------------------------------------------------------------------
# Load app_sim(n) submodules

source [file join $::athenaapp::library app.tcl      ]
source [file join $::athenaapp::library scenario.tcl ]
source [file join $::athenaapp::library sim.tcl      ]
source [file join $::athenaapp::library engine.tcl   ]
source [file join $::athenaapp::library log.tcl      ]
source [file join $::athenaapp::library cif.tcl      ]
source [file join $::athenaapp::library map.tcl      ]
source [file join $::athenaapp::library sanity.tcl   ]
source [file join $::athenaapp::library axdb.tcl     ]







