#---------------------------------------------------------------------
#
# Makefile -- Makefile for simlib(n)
#
# Targets supported:
# 
#    test     Runs the test suite.

# Configuration variables

TOP_DIR=../..
TCLSH=tclsh8.5

include $(TOP_DIR)/MakeDefs

# Target: test
test:
	$(TCLSH) simlib.test

include $(TOP_DIR)/MakeRules
